name = "synmad"
main = "_worker.js"
compatibility_date = "2024-12-20"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "211.230.110.231:50008"
UUID = "6dc49ff1-59d3-40d2-9925-faff3a30f423"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
